import type { Metadata } from "next";
import "./globals.css";
import { Cabecalho } from "@/components/Cabecalho/page";
import { Rodape } from "@/components/Rodape/page";
export const metadata: Metadata = {
  title: "NeoEnergy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
